novelai_token: []
use_token: 0
proxy:
  enable: false
  host: 127.0.0.1
  port: 7890
reverse_proxy:
  base_url: "https://image.novelai.net"
  user_url: "https://api.novelai.net"
sdapi:
  url: ""
  token: ""
translate:
  appid: ""
  appkey: ""
nsfw_check: false
api4ai:
  nsfw_threshold: 0.8
tencent:
  SecretId: ""
  SecretKey: ""
  Bucket: ""
  Region: ""
  BizType: ""
free_mode: true
forward_msg: false
paimon_nai_turnOn: true
CD_all: 90
nsfw_group: ""
usageLimit_day: 5
nai_unlimited_users:
  - 123
nai_unsafewords: "without clothes|no clothes|no cloth|sex,|nude|naked|pussy|nsfw|nipple|nipples|penis|anal|anus|clitoris|labia|urethra|topless|bottomless|bareback|threesome|69|multiple_insertions|triple_penetration|incest|paizuri|nipples|nipple_piercing|areolae|asian|bestiality|artificial_vagina|missionary|stwincest|dildo|cum_inside|panties_around_one_leg|spreader_bar|shaved_pussy|spitroast|futanari|double_penetration|double_vaginal|double_anal|hairjob|oral|fellatio|gag,|vore|gokkun|breast_sucking|nipple_suck|lactation|nipple_pull|breast_feeding|tally|facesitting|virgin|multiple_paizuri|puffy_nipples|huge_ass|girl_on_top|reverse_cowgirl|cowgirl_position|nyotaimori|femdom|pegging|cervix|slave|leash|wide_hips|ejaculation|cum_on_hair|cum_on_food|about_to_be_raped|censored|small_nipples|cum_on_breast|cock_ring|large_insertion|penetration|rape|happy_sex|mind_control|grinding|molestation|suspension|no shirt|pregnancy|pregnant|vagina|areola|bondage|bdsm"